# Base configs
baseurl: "https://imRish.github.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Experiments by RISH"
subtitle: "Beauty in chaos"
author: "RISH"
header:
 title: "Generative Design"
 subtitle: "by RISH"
footer:
 name: "Hey there, I am RISH."
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning generative systems."
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/therishabhpandey"
  twitter: "https://www.twitter.com/rishhere"
  instagram: "https://www.instagram.com/therishabhpandey"
  linkedin: "https://www.linkedin.com/in/rish95"
  github: "https://www.github.com/imrish"
